### PR TITLE
fix block collisions [1.21.2+]

### LINKED ISSUE #1885: Bubble columns and water pushing false in 1.21.4
### Describe the false positive and how to replicate it

https://streamable.com/b1g938

### Grim version

Latest commit https://github.com/GrimAnticheat/Grim/commit/bf37add382d89a295d731cb49b2427a9f68a6d3a

### Server version

This server is running Paper version 1.21.4-DEV-master@71a367e (2024-12-08T13:59:53Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.3-DEV-c2294d7 (MC: 1.21.3)

### Client version

1.21.4

### Plugins

Grim

### PR DESCRIPTION
**Pull request by Cyramek**
Mojang rewrote the block collision system in 1.21.2+
I also noticed that honey blocks were handled incorrectly

things that need to be looked at:
- block collisions while riding entity [now it seems correct, but I may be wrong]

fix: https://github.com/GrimAnticheat/Grim/issues/1885

### CODE REVIEW

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java [hunk 1]
```diff
@@ -457,102 +466,284 @@ public static void handleInsideBlocks(GrimPlayer player) {
...
-                        }
+        LongSet visitedBlocks = player.visitedBlocks;
+        for (Vector3i blockPos : boxTraverseBlocks(start, end, boundingBox)) {
+            WrappedBlockState blockState = player.compensatedWorld.getBlock(blockPos);
+            StateType blockType = blockState.getType();
 
-                        // Reset fall distance inside bubble column
-                        player.fallDistance = 0;
-                    }
+            if (!blockState.getType().isAir() && visitedBlocks.add(GrimMath.asLong(blockPos))) {
```
Comment (SamB440) [inline src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java]: I think what Mojang is doing here is checking if the block was already visited. Can't we make boxTraverseBlocks use sets to only return unique Vector3i's, removing this "visitedBlocks" entirely?

Comment (Cyramek) [reply src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java]: in theory, Collisions#boxTraverseBlocks should never return duplicates (at least, I can't see when this could happen)
```java
    public static Iterable<Vector3i> boxTraverseBlocks(Vector3d start, Vector3d end, SimpleCollisionBox boundingBox) {
        Vector3d direction = end.subtract(start);
        Iterable<Vector3i> initialBlocks = SimpleCollisionBox.betweenClosed(boundingBox);
        if (direction.lengthSquared() < (double) GrimMath.square(0.99999F)) {
            return initialBlocks;
        } else {
            Set<Vector3i> traversedBlocks = new ObjectLinkedOpenHashSet<>();
            Vector3d boxMinPosition = boundingBox.getMinPosition();
            Vector3d subtractedMinPosition = boxMinPosition.subtract(direction);
            addCollisionsAlongTravel(traversedBlocks, subtractedMinPosition, boxMinPosition, boundingBox);

            for (Vector3i blockPos : initialBlocks) {
                traversedBlocks.add(blockPos);
            }

            return traversedBlocks;
        }
    }
```

**Comment by SamB440** [comment]
What about betweenClosed?

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java (hunk 1 above)
Comment (SamB440) [reply src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java]: What about betweenClosed?

Comment (Cyramek) [reply src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java]:
```java
    public static Iterable<Vector3i> betweenClosed(SimpleCollisionBox box) {
        Vector3i startBlockPos = containing(box.minX, box.minY, box.minZ);
        Vector3i endBlockPos = containing(box.maxX, box.maxY, box.maxZ);
        return betweenClosed(startBlockPos, endBlockPos);
    }

    public static Vector3i containing(double x, double y, double z) {
        return new Vector3i(GrimMath.floor(x), GrimMath.floor(y), GrimMath.floor(z));
    }

    public static Iterable<Vector3i> betweenClosed(Vector3i firstPos, Vector3i secondPos) {
        return betweenClosed(
                Math.min(firstPos.getX(), secondPos.getX()),
                Math.min(firstPos.getY(), secondPos.getY()),
                Math.min(firstPos.getZ(), secondPos.getZ()),
                Math.max(firstPos.getX(), secondPos.getX()),
                Math.max(firstPos.getY(), secondPos.getY()),
                Math.max(firstPos.getZ(), secondPos.getZ())
        );
    }

    public static Iterable<Vector3i> betweenClosed(int xStart, int yStart, int zStart, int xEnd, int yEnd, int zEnd) {
        int xRange = xEnd - xStart + 1;
        int yRange = yEnd - yStart + 1;
        int zRange = zEnd - zStart + 1;
        int totalVectors = xRange * yRange * zRange;
        return () -> new AbstractIterator<>() {
            private int index;

            @Override
            protected Vector3i computeNext() {
                if (this.index == totalVectors) {
                    return this.endOfData();
                } else {
                    int xOffset = this.index % xRange;
                    int yOffset = this.index / xRange;
                    int yOffsetMod = yOffset % yRange;
                    int zOffset = yOffset / yRange;
                    this.index++;
                    return new Vector3i(xStart + xOffset, yStart + yOffsetMod, zStart + zOffset);
                }
            }
        };
    }
```

as long as I haven't overlooked anything, iterating over this index should never produce a duplicate of Vector3i

but we can do this just to be sure:
```java
    public static Set<Vector3i> boxTraverseBlocks(Vector3d start, Vector3d end, SimpleCollisionBox boundingBox) {
        Vector3d direction = end.subtract(start);
        Iterable<Vector3i> initialBlocks = SimpleCollisionBox.betweenClosed(boundingBox);
        if (direction.lengthSquared() < (double) GrimMath.square(0.99999F)) {
            Set<Vector3i> traversedBlocks = new ObjectLinkedOpenHashSet<>();

            for (Vector3i blockPos : initialBlocks) {
                traversedBlocks.add(blockPos);
            }

            return traversedBlocks;
        } else {
            Set<Vector3i> traversedBlocks = new ObjectLinkedOpenHashSet<>();
            Vector3d boxMinPosition = boundingBox.getMinPosition();
            Vector3d subtractedMinPosition = boxMinPosition.subtract(direction);
            addCollisionsAlongTravel(traversedBlocks, subtractedMinPosition, boxMinPosition, boundingBox);

            for (Vector3i blockPos : initialBlocks) {
                traversedBlocks.add(blockPos);
            }

            return traversedBlocks;
        }
    }
```

File: src/main/java/ac/grim/grimac/utils/math/GrimMath.java [hunk 2]
```diff
@@ -87,6 +88,22 @@ public static long lfloor(double p_14135_) {
...
+        } else {
+            return x > 0.0 ? 1 : -1;
+        }
+    }
+
+    public static float square(float value) {
+        return value * value;
+    }
+
+    public static long asLong(Vector3i pos) {
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/math/GrimMath.java]: doesn't `pos.getSerializedPosition()` do the same thing?

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java (hunk 1 above)
Comment (ManInMyVan) [reply src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java]: I doubt it can produce duplicates

File: src/main/java/ac/grim/grimac/utils/math/GrimMath.java (hunk 2 above)
Comment (Cyramek) [reply src/main/java/ac/grim/grimac/utils/math/GrimMath.java]: Vector3i#getSerializedPosition uses the server version to determine how to serialize the position. Theoretically, it should work as expected, but I am going to remove this part of the code later, as it is currently used only to serialize the position for already visited blocks

File: src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java [hunk 3]
```diff
@@ -513,20 +523,77 @@ public int size() {
...
+        return maxX - minX;
+    }
+
+    public double getYsize() {
+        return maxY - minY;
+    }
+
+    public double getZsize() {
+        return maxZ - minZ;
+    }
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java]:
```suggestion
    public double getXSize() {
        return maxX - minX;
    }

    public double getYSize() {
        return maxY - minY;
    }

    public double getZSize() {
        return maxZ - minZ;
    }
```

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java [hunk 4]
```diff
@@ -457,102 +462,284 @@ public static void handleInsideBlocks(GrimPlayer player) {
...
-                            }
-                        }
+        for (Vector3i blockPos : boxTraverseBlocks(start, end, boundingBox)) {
+            WrappedBlockState blockState = player.compensatedWorld.getBlock(blockPos);
+            StateType blockType = blockState.getType();
 
-                        // Reset fall distance inside bubble column
-                        player.fallDistance = 0;
-                    }
+            if (blockType.isAir()) {
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java:574]: do we even need to do this? Air doesn't handled anyway

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java (hunk 4 above)
Comment (Cyramek) [reply src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java:574]: serve as a fast-fail mechanism to avoid calling methods in the most common case

File: src/main/java/ac/grim/grimac/utils/math/GrimMath.java [hunk 5]
```diff
@@ -87,6 +87,18 @@ public static long lfloor(double p_14135_) {
         return p_14135_ < (double) i ? i - 1L : i;
     }
 
+    public static int sign(double x) {
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/math/GrimMath.java:90]: does this consider NaN? It looks like it would return -1 for any NaN value (is this intentional?), I think this should return 0 for NaN values, since casting NaN to an int yields 0.

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java [hunk 6]
```diff
@@ -457,102 +461,288 @@ public static void handleInsideBlocks(GrimPlayer player) {
...
+                }
+            }
+        }
+    }
 
-                    if (blockType == StateTypes.POWDER_SNOW && blockX == Math.floor(player.x) && blockY == Math.floor(player.y) && blockZ == Math.floor(player.z)
-                            && player.getClientVersion().isNewerThanOrEquals(ClientVersion.V_1_17)) {
-                        player.stuckSpeedMultiplier = new Vector(0.8999999761581421, 1.5, 0.8999999761581421);
-                    }
+    public static void onInsideBlock(GrimPlayer player, StateType blockType, WrappedBlockState block, int blockX, int blockY, int blockZ) {
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java:474]: are there any differences between this method and the code before? (don't wanna look through the diff)

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java [hunk 7]
```diff
@@ -457,102 +461,288 @@ public static void handleInsideBlocks(GrimPlayer player) {
...
+            double maxOtherB,
+            Direction hitSide,
+            double startSide,
+            double startOtherA,
+            double startOtherB
+    ) {
+        double sideDistance = (minSide - startSide) / distanceSide;
+        double otherDistanceA = startOtherA + sideDistance * distanceOtherA;
+        double otherDistanceB = startOtherB + sideDistance * distanceOtherB;
+        if (0.0 < sideDistance && sideDistance < minDistance[0] && minOtherA - COLLISION_EPSILON < otherDistanceA && otherDistanceA < maxOtherA + COLLISION_EPSILON && minOtherB - COLLISION_EPSILON < otherDistanceB && otherDistanceB < maxOtherB + COLLISION_EPSILON) {
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java]: 1. this if statement should be broken up into multiple lines
2. In the first condition the constant and variable should be swapped

File: src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java [hunk 8]
```diff
@@ -513,20 +523,77 @@ public int size() {
...
+                    int xOffset = this.index % xRange;
+                    int yOffset = this.index / xRange;
+                    int yOffsetMod = yOffset % yRange;
+                    int zOffset = yOffset / yRange;
+                    this.index++;
+                    return new Vector3i(xStart + xOffset, yStart + yOffsetMod, zStart + zOffset);
+                }
+            }
+        };
+    }
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java:595]: all of this is copy pasted from vanilla right? (with variable deobf)

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java [hunk 9]
```diff
@@ -457,102 +461,288 @@ public static void handleInsideBlocks(GrimPlayer player) {
...
+            minDistance[0] = sideDistance;
+            return hitSide;
+        } else {
+            return prevDirection;
+        }
+    }
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java]: all of this is copy pasted from vanilla right? (with variable deobf)

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

File: src/main/java/ac/grim/grimac/utils/math/GrimMath.java (hunk 5 above)
Comment (Cyramek) [reply src/main/java/ac/grim/grimac/utils/math/GrimMath.java:90]: it's mojang's code

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java (hunk 6 above)
Comment (Cyramek) [reply src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java:474]: only honey blocks, https://github.com/GrimAnticheat/Grim/pull/2015/commits/2e05f155e447781e7f81d9810aa734ae1a28607c

File: src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java (hunk 8 above)
Comment (Cyramek) [reply src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java:595]: yeah

File: src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java (hunk 9 above)
Comment (Cyramek) [reply src/main/java/ac/grim/grimac/utils/nmsutil/Collisions.java]: yeah

File: src/main/java/ac/grim/grimac/utils/math/GrimMath.java (hunk 5 above)
Comment (ManInMyVan) [reply src/main/java/ac/grim/grimac/utils/math/GrimMath.java:90]: sure but add a comment saying it's that value squared, so if it gets changed in the future it's easier to spot

**Review by ManInMyVan — APPROVED** [review]

**Comment by Huge-mistake** [comment]
Can it be merged? There is an urgent need for this.

**Comment by Cyramek** [comment]
> Can it be merged? There is an urgent need for this.

you can download the jar from this branch here:
https://github.com/Cyramek/Grim/actions/runs/13784683865

if you find any issues, please report them in this issue

**Review by Axionize — APPROVED** [review]
