### PR TITLE
[1.21.10] Rewrite block effects, LpVector support, partially implemented collision boxes

### LINKED ISSUE #2270: False positive when boat enter soul sand bubble column
### Describe the false positive and how to replicate it

`Grim » player failed Simulation (x21) .240462 /gl 22`

The vanilla behavior should be that player floats up in the boat, and should not leave the boat

https://github.com/user-attachments/assets/c40f0114-443e-4180-9856-230d11ebcfd2

### Grim version

`Grim Version 2.3.72-f739b1e39`

### Server version

`Purpur version 1.21.8-2495-HEAD@db12e9b`

### Client version

1.21.8

### Plugins

GrimAC

### PR DESCRIPTION
**Pull request by Cyramek**
ah shit here we go again

things that need to happen before this can be merged:

- [x] packetevents update
- [x] test every version

fix: https://github.com/GrimAnticheat/Grim/issues/2270

### CODE REVIEW

File: common/src/main/java/ac/grim/grimac/predictionengine/blockeffects/BlockCollisions.java [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+
+import ac.grim.grimac.utils.nmsutil.Collisions;
+import com.github.retrooper.packetevents.protocol.world.Direction;
+import com.github.retrooper.packetevents.util.Vector3d;
+import com.github.retrooper.packetevents.util.Vector3i;
+import com.google.common.collect.ImmutableList;
+
+import java.util.Optional;
+
+public class BlockCollisions {
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/predictionengine/blockeffects/BlockCollisions.java:13]: `@UtilityClass`?

**Review by ManInMyVan — CHANGES_REQUESTED** [review]
I think BlockEffectsResolverV1_21_10 would look better

**Comment by ManInMyVan** [comment]
also remember to make sure your changes don't break older versions

**Comment by Cyramek** [comment]
> also remember to make sure your changes don't break older versions

initial tests do not show any form of regression, however I rewrote entire collision code from scratch, so I need to run more tests

File: common/src/main/java/ac/grim/grimac/predictionengine/blockeffects/impl/BlockEffectsResolverV1_21_10.java [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+    public static int addCollisionsAlongTravel(LongSet alreadyVisited, Vector3d direction, SimpleCollisionBox boundingBox, BlockStepVisitor visitor) {
+        double sizeX = boundingBox.getXSize();
+        double sizeY = boundingBox.getYSize();
+        double sizeZ = boundingBox.getZSize();
+
+        Vector3i furthestCorner = BlockCollisions.getFurthestCorner(direction);
+
+        Vector3d center = boundingBox.getCenter();
+        Vector3d vec33 = new Vector3d(center.x + sizeX * 0.5 * furthestCorner.getX(), center.y + sizeY * 0.5 * furthestCorner.getY(), center.z + sizeZ * 0.5 * furthestCorner.getZ());
+        Vector3d vec34 = vec33.subtract(direction);
```
Comment (Cyramek) [inline common/src/main/java/ac/grim/grimac/predictionengine/blockeffects/impl/BlockEffectsResolverV1_21_10.java]: deobf whatever this is

File: common/src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java [hunk 3]
```diff
@@ -554,6 +592,93 @@ protected Vector3i computeNext() {
...
+                    return this.cursor;
+                }
+            }
+        };
+    }
+
+    private static double get(Vector3d vector, Collisions.Axis axis) {
+        return axis.choose(vector.x, vector.y, vector.z);
+    }
+
```
Comment (Cyramek) [inline common/src/main/java/ac/grim/grimac/utils/collisions/datatypes/SimpleCollisionBox.java]: deobf whatever this is

**Comment by ManInMyVan** [comment]
I'd consider moving Collisions$Axis to a seperate class

File: common/src/main/java/ac/grim/grimac/checks/impl/velocity/VectorPrecisionConverter.java [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+import lombok.experimental.UtilityClass;
+
+@UtilityClass
+public class VectorPrecisionConverter {
+
+    private static final ServerVersion SERVER_VERSION = PacketEvents.getAPI().getServerManager().getVersion();
+
+    public static Vector3d convert(ClientVersion version, Vector3d vector) {
+        if (version.isNewerThanOrEquals(ClientVersion.V_1_21_9) && SERVER_VERSION.isOlderThanOrEquals(ServerVersion.V_1_21_8)) {
+            vector = VectorPrecisionConverter.legacyToLp(vector);
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/checks/impl/velocity/VectorPrecisionConverter.java]:
```suggestion
            return VectorPrecisionConverter.legacyToLp(vector);
```

File: common/src/main/java/ac/grim/grimac/checks/impl/velocity/VectorPrecisionConverter.java [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+        } else if (version.isOlderThanOrEquals(ClientVersion.V_1_21_7) && SERVER_VERSION.isNewerThanOrEquals(ServerVersion.V_1_21_9)) {
+            vector = VectorPrecisionConverter.lpToLegacy(vector);
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/checks/impl/velocity/VectorPrecisionConverter.java]:
```suggestion
            return VectorPrecisionConverter.lpToLegacy(vector);
```

File: common/src/main/java/ac/grim/grimac/predictionengine/blockeffects/BlockCollisions.java [hunk 6]
```diff
@@ -0,0 +1,127 @@
...
+            double startOtherB
+    ) {
+        double sideDistance = (minSide - startSide) / distanceSide;
+        double otherDistanceA = startOtherA + sideDistance * distanceOtherA;
+        double otherDistanceB = startOtherB + sideDistance * distanceOtherB;
+        if (sideDistance > 0.0 && sideDistance < minDistance[0] &&
+                minOtherA - Collisions.COLLISION_EPSILON < otherDistanceA &&
+                otherDistanceA < maxOtherA + Collisions.COLLISION_EPSILON &&
+                minOtherB - Collisions.COLLISION_EPSILON < otherDistanceB &&
+                otherDistanceB < maxOtherB + Collisions.COLLISION_EPSILON) {
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/predictionengine/blockeffects/BlockCollisions.java]: ands on the start of the line

File: common/src/main/java/ac/grim/grimac/predictionengine/predictions/rideable/PredictionEngineBoat.java [hunk 7]
```diff
@@ -186,6 +186,10 @@ public Set<VectorData> fetchPossibleStartTickVectors(GrimPlayer player) {
     public void endOfTick(GrimPlayer player, double d) {
         super.endOfTick(player, d);
         Collisions.handleInsideBlocks(player);
+
+        // yes, this is how mojank does it
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/predictionengine/predictions/rideable/PredictionEngineBoat.java:190]: is this how they do it in legacy versions like 1.8 and 1.12 too?

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

File: common/src/main/java/ac/grim/grimac/predictionengine/predictions/rideable/PredictionEngineBoat.java (hunk 7 above)
Comment (Cyramek) [reply common/src/main/java/ac/grim/grimac/predictionengine/predictions/rideable/PredictionEngineBoat.java:190]:
```java
    // Implementation of Collisions#handleInsideBlocks for >= 1.21.2
    public static void applyEffectsFromBlocks(GrimPlayer player) {
        if (player.getClientVersion().isOlderThan(ClientVersion.V_1_21_2)) {
            return;
        }
```

```java
    public static void handleInsideBlocks(GrimPlayer player) {
        // Mojang rewrote this whole logic in 1.21.2 (see Collisions#applyEffectsFromBlocks)
        if (player.getClientVersion().isNewerThanOrEquals(ClientVersion.V_1_21_2)) return;
```

these methods check if they can be executed
