### PR TITLE
1.21.5/.6/.7

### LINKED ISSUE #1929: Slabs over honey block
### Describe the false positive and how to replicate it

Place slab atop honey blocks, grim simulation fails

https://github.com/user-attachments/assets/75d4d1bc-87fe-495e-ae2f-4ecc232bc554

### Grim Log

N/A

### Server version

This server is running Paper version 1.21.4-DEV-main@49d15f6 (1970-01-01T00:00:00Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-DEV-3375570 (MC: 1.21.4)

### Client version

1.21.4

### Plugins

GrimAC version f852f16c9c058fcba091ca1d0e4139e9c70de86d (latest)

### LINKED ISSUE #2090: Simulation riding horse broken 1.21.5
### Describe the false positive and how to replicate it

Ride a horse, huge .4+ offset simulation flags

### Grim Log

Grim 50b360dd093ac111a6a85710711d7d3d57eb2ce6

### Server version

This server is running Paper version 1.21.5-DEV-main@3409e2d (1970-01-01T00:00:00Z) (Implementing API version 1.21.5-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.5-DEV-9cddf13 (MC: 1.21.5)

### Client version

1.21.5

### Plugins

N/A

### PR DESCRIPTION
**Pull request by Cyramek**
todo:
- happyghast movement
- collisionboxes/hitboxes (and viaversion replacements) for new blocks in .5/.6

fix: https://github.com/GrimAnticheat/Grim/issues/2090
fix: https://github.com/GrimAnticheat/Grim/issues/1929

### CODE REVIEW

**Comment by Krymonota** [comment]
Another thing that came to mind: Minecraft 1.21.5 added a new component called `minecraft:blocks_attacks` that also slows the player down when blocking. Maybe this should be taken into account? https://github.com/GrimAnticheat/Grim/blob/efbb66c8d89e8775638d301f57710990902bc7b6/common/src/main/java/ac/grim/grimac/events/packets/PacketPlayerDigging.java#L50

**Comment by FellowNeighbour** [comment]
I've noticed that 1.21.5 clients that are elytra flying and pass through a vine will start rubberbanding.

**Comment by Cyramek** [comment]
> I've noticed that 1.21.5 clients that are elytra flying and pass through a vine will start rubberbanding.

should be fixed in this branch, lmk if that's not the case

**Comment by Dbbtop** [comment]
When will this PR be ready? Version 1.21.6 has already been released

**Comment by FellowNeighbour** [comment]
Any potential ETA on when this will be done and ready to merge?

**Comment by Cyramek** [comment]
> Any potential ETA on when this will be done and ready to merge?

I believe the only thing needed right now is the update to grim's packetevents fork,
once that's done, this pull request can be reviewed and eventually merged, other changes can be handled in separate commits/pr

**Comment by FellowNeighbour** [comment]
> > Any potential ETA on when this will be done and ready to merge?
> 
> I believe the only thing needed right now is the update to grim's packetevents fork, once that's done, this pull request can be reviewed and eventually merged, other changes can be handled in separate commits/pr

Wonderful, thank you for your contributions.

**Comment by FellowNeighbour** [comment]
Paper has just released stable 1.21.6 builds, it would be nice to see this get merged soon.

**Comment by ghost** [comment]
bom bom bom bom bom bom bom bom bom bom bom bom bom
Mr Diffman, bring me a diff, 
make it the biggest that i've ever seen, 
make it late, long after 1.21.8
refactor every label, long after paper stable
make it a draft, that will be a laugh
make it hard for those to review, such that it will never get through!

All jokes aside, I'm working on my own 1.21.6 PR for the most important stuff at #2173 and it is ready to be merged.

File: common/src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java [hunk 1]
```diff
@@ -123,8 +125,20 @@ public void onPacketReceive(PacketReceiveEvent event) {
...
+                inputVector = PredictionEngine.modifyInput(player, new Vec2(forward, sideways).normalized());
+            } else {
+                inputVector = new Vec2(forward * 0.98f, sideways * 0.98f);
+            }
+
+            player.vehicleData.nextVehicleForward = inputVector.x();
+            player.vehicleData.nextVehicleHorizontal = inputVector.y();
+
+            // that's how mojang is dealing with sneaking from now on...
+            if (player.getClientVersion().isNewerThanOrEquals(ClientVersion.V_1_21_6)) {
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java]: this should also check server version

File: common/src/main/java/ac/grim/grimac/player/GrimPlayer.java [hunk 2]
```diff
@@ -266,8 +268,7 @@ public class GrimPlayer implements GrimUser {
     // This variable is for support with test servers that want to be able to disable grim
     // Grim disabler 2022 still working!
     public boolean disableGrim = false;
-    // TODO: teleport clear this?
-    public final List<List<Movement>> movementThisTick = new ObjectArrayList<>();
+    public final ArrayDeque<Movement> movementThisTick = new ArrayDeque<>(100);
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/player/GrimPlayer.java]: does it need to be this big? I don't think this is used at all on older versions

File: common/src/main/java/ac/grim/grimac/player/GrimPlayer.java [hunk 3]
```diff
@@ -912,7 +917,18 @@ public void resyncPositions(SimpleCollisionBox box) {
                 GrimMath.ceil(box.maxX), GrimMath.ceil(box.maxY), GrimMath.ceil(box.maxZ));
     }
 
-    public record Movement(Vector3d from, Vector3d to) {}
+    public void addMovementThisTick(GrimPlayer.Movement movement) {
+        if (this.movementThisTick.size() >= 100) {
+            GrimPlayer.Movement movement1 = this.movementThisTick.removeFirst();
+            GrimPlayer.Movement movement2 = this.movementThisTick.removeFirst();
+            GrimPlayer.Movement movement3 = new GrimPlayer.Movement(movement1.from(), movement2.to(), false);
+            this.movementThisTick.addFirst(movement3);
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/player/GrimPlayer.java:925]: it looks like this should have a return

File: common/src/main/java/ac/grim/grimac/utils/item/TridentItem.java [hunk 4]
```diff
@@ -0,0 +1,25 @@
+package ac.grim.grimac.utils.item;
+
+import ac.grim.grimac.player.GrimPlayer;
+import ac.grim.grimac.utils.latency.CompensatedWorld;
+import com.github.retrooper.packetevents.PacketEvents;
+import com.github.retrooper.packetevents.protocol.item.ItemStack;
+import com.github.retrooper.packetevents.protocol.item.enchantment.type.EnchantmentTypes;
+import com.github.retrooper.packetevents.protocol.player.InteractionHand;
+
+public class TridentItem extends ItemBehaviour {
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/utils/item/TridentItem.java:10]: why does this not have an INSTANCE field like the others?

File: common/src/main/java/ac/grim/grimac/utils/item/ItemBehaviourRegistry.java [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+    );
+
+    public static @NotNull ItemBehaviour getItemBehaviour(ItemType type) {
+        ItemBehaviour itemBehaviour = ITEM_MAPPING.get(type);
+
+        if (itemBehaviour != null) {
+            return itemBehaviour;
+        }
+
+        return ItemBehaviour.INSTANCE;
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/utils/item/ItemBehaviourRegistry.java]: why not use getOrDefault?

File: common/src/main/java/ac/grim/grimac/predictionengine/movementtick/MovementTicker.java [hunk 6]
```diff
@@ -453,13 +444,22 @@ public void livingEntityTravel() {
...
-                new PredictionEngineElytra().guessBestMovement(0, player);
+                    doNormalMove(blockFriction);
 
+                    player.isGliding = false;
+                    player.pointThreeEstimator.updatePlayerGliding(); // TODO: should this be true even if player stopped gliding?
+                } else {
+                    player.friction = 0.99F; // Not vanilla, just useful for other grim stuff
+                    // Set fall distance to 1 if the player’s y velocity is greater than -0.5 when falling
+                    if (player.clientVelocity.getY() > -0.5)
+                        player.fallDistance = 1;
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/predictionengine/movementtick/MovementTicker.java:459]: brackets?

File: common/src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java [hunk 7]
```diff
@@ -123,8 +125,20 @@ public void onPacketReceive(PacketReceiveEvent event) {
                 sideways--;
             }
 
-            player.vehicleData.nextVehicleForward = forward * 0.98f;
-            player.vehicleData.nextVehicleHorizontal = sideways * 0.98f;
+            Vec2 inputVector;
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java]: ternary maybe?

File: common/src/main/java/ac/grim/grimac/utils/item/ItemBehaviour.java [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+                final ItemEquippable equippable = item.getComponentOr(ComponentTypes.EQUIPPABLE, null);
+
+                return (equippable == null || !equippable.isSwappable()) && blocksAttacks != null;
+            }
+
+            return false;
+        }
+    }
+
+    protected boolean startConsuming(ItemStack item, CompensatedWorld world, GrimPlayer player, InteractionHand hand, ItemConsumable consumable) {
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/utils/item/ItemBehaviour.java]: `startConsuming` seems like a method with side effects, of which this does not appear to have

File: common/src/main/java/ac/grim/grimac/player/GrimPlayer.java [hunk 9]
```diff
@@ -774,6 +775,10 @@ public boolean canUseGameMasterBlocks() {
         return getClientVersion().isOlderThanOrEquals(ClientVersion.V_1_10) || (gamemode == GameMode.CREATIVE && compensatedEntities.self.opLevel >= 2);
     }
 
+    public boolean isInWaterOrRain() {
+        return this.compensatedWorld.isRaining || Collisions.hasMaterial(this, this.boundingBox.copy().expand(0.1f), (block) -> Materials.isWater(CompensatedWorld.blockVersion, block.first()));
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/player/GrimPlayer.java]: sky check for rain? unless this is what vanilla has?

**Review by ManInMyVan — DISMISSED** [review]

File: common/src/main/java/ac/grim/grimac/player/GrimPlayer.java (hunk 3 above)
Comment (Cyramek) [reply common/src/main/java/ac/grim/grimac/player/GrimPlayer.java:925]: this is what mojang does, code inside that if statement merges 2 movement records into one, and then adds a new one

movementThisTick could grow almost infinitely large server-side without this sanity check, but it's the same code on the client

File: common/src/main/java/ac/grim/grimac/player/GrimPlayer.java (hunk 9 above)
Comment (Cyramek) [reply common/src/main/java/ac/grim/grimac/player/GrimPlayer.java]: you can use trident enchanted with Riptide either when you're in water or it's raining

File: common/src/main/java/ac/grim/grimac/player/GrimPlayer.java (hunk 2 above)
Comment (Cyramek) [reply common/src/main/java/ac/grim/grimac/player/GrimPlayer.java]: 8 seems reasonable for client-side, lmk what you think

File: common/src/main/java/ac/grim/grimac/player/GrimPlayer.java (hunk 9 above)
Comment (Cyramek) [reply common/src/main/java/ac/grim/grimac/player/GrimPlayer.java]: you can see it there, this is already a thing in Grim https://github.com/GrimAnticheat/Grim/pull/2079/commits/a85caf0274f1601d5d2fa02d7d78b520ee46c109

File: common/src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java [hunk 10]
```diff
@@ -18,6 +20,8 @@
 
 public class PacketPlayerSteer extends PacketListenerAbstract {
 
+    public static final boolean SERVER_USE_INPUT_FOR_SNEAKING = PacketEvents.getAPI().getServerManager().getVersion().isNewerThanOrEquals(ServerVersion.V_1_21_6);
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/events/packets/PacketPlayerSteer.java]:
```suggestion
    public static final boolean SERVER_USES_INPUT_FOR_SNEAKING = PacketEvents.getAPI().getServerManager().getVersion().isNewerThanOrEquals(ServerVersion.V_1_21_6);
```

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

**Comment by Axionize** [comment]
I've talked with @Cyramek about it and while the updates are not complete they've agreed to have these changes merged to prevent them from piling up forever and delaying the time till uses see these fixes.  

Incomplete version changes will now be merged periodically at points marked stable, and future work will be done on the new head of the repo incorporating other changes and the new version-specific updates.
