### PR TITLE
[POC] bouncy blocks fix

### LINKED ISSUE #760: False positive when jumping between or walking off beds
### Describe the false positive and how to replicate it

Step one: Setup 2 beds beside each other, with 2 blocks of space in between and blocks on the outside.
Step two: Repetedly jump between them. Grim will trigger.
[Video(mp4)](https://cdn.discordapp.com/attachments/1009113383557136506/1010555947451695154/AnticheatTrigger.mp4)

### Grim version

2.3.23

### Server version

Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

### Plugins

CoreProtect, dynmap, Essentials, EssentialsChat, GrimAC, LuckPerms, ProtocolLib, ServerlistMOTD*, Vault

### LINKED ISSUE #1389: Slime edges flag in 1.8.9
### Describe the false positive and how to replicate it

https://github.com/GrimAnticheat/Grim/assets/118249487/dab5b797-a043-4de0-aa6a-55439ed60e01

### Grim version

2.3.59

### Server version

I dont know, its eu.loyisa.cn (/version seems to be disabled)
Minecraft 1.8.9

### Plugins

I dont know, its eu.loyisa.cn (/version seems to be disabled)

### LINKED ISSUE #1392: Bed & chain falses
### Describe the false positive and how to replicate it

step 1. place a bed
step 2. walk on and off the bed; usually corners
step 3. this will false simulation

step 1. place chains
step 2. walk on the chains
step 3. this will also false simulation

note: this also falses on servers other than mine

### Grim version

2.3.59

### Server version

git-Purpur-2155 (MC: 1.20.4)*

### Plugins

Chunky, CoreProtect, DangerLevel, Factions, GraveStonesPlus, GrimAC, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LiteBans, LuckPerms, mcMMO, *ObsidianDestroyer, SkBee, Skript, skript-reflect, spark, TwerkGrowth, VanishNoPacket, Vault, VeinMiner, ViaBackwards, ViaVersion, Vulcan, WorldEdit

### LINKED ISSUE #1873: walking off slime
### Describe the false positive and how to replicate it

https://github.com/user-attachments/assets/ee4d5f76-abd6-446a-9d34-8992ecef1936

### Grim Log

gl 8: https://paste.grim.ac/x7itp1k

### Server version

pandaspigot 1.8.8

### Client version

1.20.4 vanilla

### Plugins

Apollo-Bukkit, WorldEdit, AnticheatToggler, BadlionClientModAPI, PlaceholderAPI, AntiDisconnectSpam, spark, ViaVersion, LightAntiCheat, ViaBackwards, ProtocolLib, WorldGuard, ViaRewind, NoCheatPlus, LuckPerms, SimpleScore, ViaRewind-Legacy-Support, Vault, Citizens, Sentinel, Essentials, GrimAC

### PR DESCRIPTION
**Pull request by Cyramek**
this PR does not implement bouncy blocks correctly, but rather tries to improve the current approach to handling these blocks.

this code is running in production currently and I did not find any issues this could cause
that said, I'm not entirely sure that this PR is 100% correct and does not break anything that is currently working.

most likely fixes:
fix: https://github.com/GrimAnticheat/Grim/issues/1873
fix: https://github.com/GrimAnticheat/Grim/issues/1392
fix: https://github.com/GrimAnticheat/Grim/issues/760
fix: https://github.com/GrimAnticheat/Grim/issues/1389

### CODE REVIEW

File: common/src/main/java/ac/grim/grimac/predictionengine/MovementCheckRunner.java [hunk 1]
```diff
@@ -374,16 +374,18 @@ private void check(PositionUpdate update) {
             player.packetStateData.lastRiptide = currentTime;
         }
 
-        SimpleCollisionBox steppingOnBB = GetBoundingBox.getCollisionBoxForPlayer(player, player.x, player.y, player.z).expand(player.getMovementThreshold()).offset(0, -1, 0);
-        Collisions.hasMaterial(player, steppingOnBB, (pair) -> {
-            WrappedBlockState data = pair.first();
+        SimpleCollisionBox steppingOnBB = GetBoundingBox.getCollisionBoxForPlayer(player, player.lastX, player.lastY, player.lastZ)
+                .offset(0.0, player.getClientVersion().isOlderThan(ClientVersion.V_1_15) ? -1.0 : -0.2, 0.0);
```
Comment (SamB440) [inline common/src/main/java/ac/grim/grimac/predictionengine/MovementCheckRunner.java:378]: Not expanding by movement threshold is wrong. The correct way is to run collisions for each 0.03 axis.

Comment (SamB440) [reply common/src/main/java/ac/grim/grimac/predictionengine/MovementCheckRunner.java:378]: But I doubt this is easily done on 2.0

**Comment by lokspel** [comment]
@SamB440
