### PR TITLE
Fix some issues with BadPacketsZ

### LINKED ISSUE #1512: False positive: mcMMO - BadPacketsZ
### Describe the false positive and how to replicate it

1. Use the Super Breaker ability in mcMMO

Would there be the possibility for Grim to support mcMMO abilities?
We temporarily fixed this issue by disabling BadPacketsZ.

image

### Grim version

Grim 2.3.65

### Server version

```
Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2169 (MC: 1.20.4)
* You are running the latest version
```

### Plugins

image

### PR DESCRIPTION
**Pull request by ManInMyVan**
fixes #1512, unnecessary exemptions, and a false when looking away from the block and then back at it

### CODE REVIEW

File: src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsZ.java [hunk 1]
```diff
@@ -47,43 +47,43 @@ private String formatted(Vector3i vec) {
...
             }
 
-            exemptNextFinish = false;
-
-            if ((lastBlock == null || !lastBlock.equals(dig.getBlockPosition())) && (lastLastBlock == null || !lastLastBlock.equals(dig.getBlockPosition()))) {
-                if (flagAndAlert("action=CANCELLED_DIGGING, last=" + formatted(lastBlock) + "/" + formatted(lastLastBlock) + ", pos=" + formatted(dig.getBlockPosition()))) {
-                    if (shouldModifyPackets()) {
-                        event.setCancelled(true);
-                        player.onPacketCancel();
+            if (!dig.getBlockPosition().equals(lastBlock)) {
```
Comment (SamB440) [inline src/main/java/ac/grim/grimac/checks/impl/badpackets/BadPacketsZ.java]: I would make `dig.getBlockPosition` a variable since it's used a lot
