### PR TITLE
Fix AirLiquidPlace falses (and BadPacketsX false)

### LINKED ISSUE #1508: BadPacketsX and AirLiquidPlace false flag
### Describe the false positive and how to replicate it

Video: https://www.youtube.com/watch?v=ybu9m79lSfw

replicated on vanilla/forge without mods 1.18.1 and 1.20.4

### Grim version

2.3.64

### Server version

1.8.8 (mc.loyisa.cn)

### Plugins

ViaVersion 4.10.2

### PR DESCRIPTION
**Pull request by Axionize**
The comments in the code explain everything very clearly and in detail.

This also indirectly fixes a BadPacketsX false which is triggered together when AirLiquidPlace fails in rapid succession multiple times in a tick.

```
    /* This check has been plagued by falses for ages, and I've finally figured it out.
    When breaking and placing on the same tick in the same tick, I believe the vanilla client always sends DIGGING ACTION packets first
    This check's falses all seem to stem from processing DiggingAction.START_DIGGING before PacketType.Play.Client.PLAYER_BLOCK_PLACEMENT in the same tick
    Since we process the break first, when we go to process the place it looks like the player placed against air in the async world
    We will often see:
        Async world updated: short_grass -> air at X: -32, Y: 69, Z: -240, tick 0, cause/source: DiggingAction.START_DIGGING
        AirLiquidPlace Check: Block state at X: -32, Y: 69, Z: -240 is air (valid: false), tick +0-1, cause/source: PacketType.Play.Client.PLAYER_BLOCK_PLACEMENT <---- previously falsed here
        Async world updated: air -> short_grass at X: -32, Y: 69, Z: -240, tick +3-4, cause: realtime task in applyBlockChanges(List<Vector3i> toApplyBlocks) source: PacketType.Play.Client.PONG
        Async world updated: short_grass -> air at X: -32, Y: 69, Z: -240, tick +0-1, cause: handleNettySyncTransaction(LatencyUtils.java:56) source: PacketType.Play.Client.PONG
    In addition, it is possible for:
        Async world updated: short_grass -> air at X: -49, Y: 69, Z: -190, tick 0, cause: realtime task in applyBlockChanges(List<Vector3i> toApplyBlocks) source: PacketType.Play.Client.PONG
        AirLiquidPlace Check: Block state at X: -49, Y: 69, Z: -190 is air (valid=false), tick 0 <--- false due to change from applyBlockChanges()
        Async world updated: grass_block[snowy=false] -> grass_block[snowy=false] at X: -49, Y: 69, Z: -189, tick 0, cause: handleNettySyncTransaction(LatencyUtils.java:56) source: PacketType.Play.Client.PONG
    And in even more rare cases:
        Async world updated: air -> air at X: -51, Y: 71, Z: -179, tick 0, cause: handleNettySyncTransaction(LatencyUtils.java:56) source: PacketType.Play.Client.PONG
        AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -180 is short_grass (valid=true), tick 0
        Async world updated: short_grass -> air at X: -49, Y: 70, Z: -180, tick 1, cause/source: DiggingAction.START_DIGGING <--- double dig here (see my BadPacketsX patch) this is legit behaviour. Can only be up to 2 in 1 tick though.
        Async world updated: air -> short_grass at X: -49, Y: 70, Z: -180, tick 1, cause/source: DiggingAction.START_DIGGING
        Async world updated: short_grass -> air at X: -51, Y: 70, Z: -179, tick 1, cause: realtime task in applyBlockChanges(List<Vector3i> toApplyBlocks) source: PacketType.Play.Client.PONG
        AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -179 is air (valid=false), tick 2 <--- falses here due to double dig if we only check the latest changed blockstate. We have to check all changes at the location in same tick.
        AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -179 is air (valid=true), tick 2
        All of which previously would've caused a false.
        To solve this we store recently changed blocks caused by DiggingAction.START_DIGGING (instant breaking) and check against the old block.
        Lots of other checks have similar issues, and with the new player.blockHistory we can patch those.
    So that's it right? It's unfalsable?
        Very close but not quite. Vanilla's client game desyncs, especially on a laggy connection where a player is breaking and placing grass 20 cps/sec in the same tick
        it is possible for short grass to be interacted with even if server-side the block is air much later, and it won't be accounted for because the modification isn't recent.
        This is incredibly rare, unreliable and is only triggerable if you intentionally want to false the check. Enough so that I consider a violation lvl of 2-3 to be perfect.
    */
```

EDIT: fixes https://github.com/GrimAnticheat/Grim/issues/1508, https://github.com/GrimAnticheat/Grim/issues/1403 and https://github.com/GrimAnticheat/Grim/issues/1776

### CODE REVIEW

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java [hunk 1]
```diff
@@ -1,27 +1,84 @@
...
+        AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -179 is air (valid=true), tick 2
+
+        All of which previously would've caused a false.
+        To solve this we store recently changed blocks caused by DiggingAction.START_DIGGING (instant breaking) and check against the old block.
+        Lots of other checks have similar issues, and with the new player.blockHistory we can patch those.
+
+    So that's it right? It's unfalsable?
+        Very close but not quite. Vanilla's client game desyncs, especially on a laggy connection where a player is breaking and placing grass 20 cps/sec in the same tick
+        it is possible for short grass to be interacted with even if server-side the block is air much later, and it won't be accounted for because the modification isn't recent.
+        This is incredibly rare, unreliable and is only triggerable if you intentionally want to false the check. Enough so that I consider a violation lvl of 2-3 to be reliable and 5-6 to be autobannable
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java]:
```suggestion
    /*
     * This check has been plagued by falses for ages, and I've finally figured it out.
     * When breaking and placing on the same tick in the same tick, I believe the vanilla client always sends DIGGING ACTION packets first
     * This check's falses all seem to stem from processing DiggingAction.START_DIGGING before PacketType.Play.Client.PLAYER_BLOCK_PLACEMENT in the same tick
     * Since we process the break first, when we go to process the place it looks like the player placed against air in the async world
     *
     * We will often see:
     *     Async world updated: short_grass -> air at X: -32, Y: 69, Z: -240, tick 0, cause/source: DiggingAction.START_DIGGING
     *     AirLiquidPlace Check: Block state at X: -32, Y: 69, Z: -240 is air (valid: false), tick +0-1, cause/source: PacketType.Play.Client.PLAYER_BLOCK_PLACEMENT <---- previously falsed here
     *     Async world updated: air -> short_grass at X: -32, Y: 69, Z: -240, tick +3-4, cause: realtime task in applyBlockChanges(List<Vector3i> toApplyBlocks) source: PacketType.Play.Client.PONG
     *     Async world updated: short_grass -> air at X: -32, Y: 69, Z: -240, tick +0-1, cause: handleNettySyncTransaction(LatencyUtils.java:56) source: PacketType.Play.Client.PONG
     *
     * In addition, it is possible for:
     *     Async world updated: short_grass -> air at X: -49, Y: 69, Z: -190, tick 0, cause: realtime task in applyBlockChanges(List<Vector3i> toApplyBlocks) source: PacketType.Play.Client.PONG
     *     AirLiquidPlace Check: Block state at X: -49, Y: 69, Z: -190 is air (valid=false), tick 0 <--- false due to change from applyBlockChanges()
     *     Async world updated: grass_block[snowy=false] -> grass_block[snowy=false] at X: -49, Y: 69, Z: -189, tick 0, cause: handleNettySyncTransaction(LatencyUtils.java:56) source: PacketType.Play.Client.PONG
     *
     * And in even more rare cases:
     *     Async world updated: air -> air at X: -51, Y: 71, Z: -179, tick 0, cause: handleNettySyncTransaction(LatencyUtils.java:56) source: PacketType.Play.Client.PONG
     *     AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -180 is short_grass (valid=true), tick 0
     *     Async world updated: short_grass -> air at X: -49, Y: 70, Z: -180, tick 1, cause/source: DiggingAction.START_DIGGING <--- double dig here (see my BadPacketsX patch) this is legit behaviour. Can only be up to 2 in 1 tick though.
     *     Async world updated: air -> short_grass at X: -49, Y: 70, Z: -180, tick 1, cause/source: DiggingAction.START_DIGGING
     *     Async world updated: short_grass -> air at X: -51, Y: 70, Z: -179, tick 1, cause: realtime task in applyBlockChanges(List<Vector3i> toApplyBlocks) source: PacketType.Play.Client.PONG
     *     AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -179 is air (valid=false), tick 2 <--- falses here due to double dig if we only check the latest changed blockstate. We have to check all changes at the location in same tick.
     *     AirLiquidPlace Check: Block state at X: -49, Y: 70, Z: -179 is air (valid=true), tick 2
     *
     *     All of which previously would've caused a false.
     *     To solve this we store recently changed blocks caused by DiggingAction.START_DIGGING (instant breaking) and check against the old block.
     *     Lots of other checks have similar issues, and with the new player.blockHistory we can patch those.
     *
     * So that's it right? It's unfalsable?
     *     Very close but not quite. Vanilla's client game desyncs, especially on a laggy connection where a player is breaking and placing grass 20 cps/sec in the same tick
     *     it is possible for short grass to be interacted with even if server-side the block is air much later, and it won't be accounted for because the modification isn't recent.
     *     This is incredibly rare, unreliable and is only triggerable if you intentionally want to false the check. Enough so that I consider a violation lvl of 2-3 to be reliable and 5-6 to be autobannable
```

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

**Comment by SamB440** [comment]
CheckManagerlistener still has conflicts

**Comment by Axionize** [comment]
Yes I'll fix this when we resolve https://github.com/GrimAnticheat/Grim/pull/1846 since it modifies similar lines.

**Comment by Axionize** [comment]
I've rebased it @SamB440

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java [hunk 2]
```diff
@@ -1,27 +1,85 @@
...
 import ac.grim.grimac.player.GrimPlayer;
 import ac.grim.grimac.utils.anticheat.update.BlockPlace;
+import ac.grim.grimac.utils.change.BlockModification;
 import ac.grim.grimac.utils.nmsutil.Materials;
 import com.github.retrooper.packetevents.protocol.player.GameMode;
 import com.github.retrooper.packetevents.protocol.world.states.type.StateType;
 import com.github.retrooper.packetevents.util.Vector3i;
 
+
+
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java [hunk 3]
```diff
@@ -0,0 +1,36 @@
+package ac.grim.grimac.utils.change;
+
+
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java]:
```suggestion
```

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

**Comment by Axionize** [comment]
I'll take care of this in a couple days; been pretty busy.

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java (hunk 2 above)
Comment (Axionize) [reply src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java]: Done

File: src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java (hunk 3 above)
Comment (Axionize) [reply src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java]: Done

**Comment by Axionize** [comment]
I'll merge this myself, just need someone else to give it a review and make sure everything's ready.

File: src/main/java/ac/grim/grimac/utils/change/BlockModification.java [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+import lombok.Getter;
+
+@Getter
+public class BlockModification {
+    private final WrappedBlockState oldBlockContents;
+    private final WrappedBlockState newBlockContents;
+    private final Vector3i location;
+    private final int tick;
+    private final Cause cause; // Optional enum for cause
+//    private final long time; // System time in milliseconds or nanoseconds for ordering
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/change/BlockModification.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java [hunk 5]
```diff
@@ -1,27 +1,83 @@
...
+     * So that's it right? It's unfalsable?
+     *     Very close but not quite. Vanilla's client game desyncs, especially on a laggy connection where a player is breaking and placing grass 20 cps/sec in the same tick
+     *     it is possible for short grass to be interacted with even if server-side the block is air much later, and it won't be accounted for because the modification isn't recent.
+     *     This is incredibly rare, unreliable and is only triggerable if you intentionally want to false the check. I consider a violation lvl of 2-3 to be reliable
+     *     and 5-6 to be autobannable (if you don't care about people who are deliberately trying to get themselves false banned)
+     */
     @Override
     public void onBlockPlace(final BlockPlace place) {
         if (player.gamemode == GameMode.CREATIVE) return;
+
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java:60]:
```suggestion
```

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java (hunk 5 above)
Comment (Axionize) [reply src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java:60]: I want separate the early return from the rest of the code via whitespace, I think it makes sense.

**Comment by Axionize** [comment]
@ManInMyVan any other suggestions before I merge?

File: src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java (hunk 3 above)
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+            blockHistory.removeFirst();
+        }
+    }
+
+    // Get the size of the block history
+    public int size() {
+        return blockHistory.size();
+    }
+
+    // Clear all block modifications
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java [hunk 7]
```diff
@@ -0,0 +1,36 @@
+package ac.grim.grimac.utils.change;
+
+
+import java.util.concurrent.ConcurrentLinkedDeque;
+import java.util.function.Predicate;
+
+public class PlayerBlockHistory {
+    private final ConcurrentLinkedDeque<BlockModification> blockHistory = new ConcurrentLinkedDeque<>();
+
+    // Add a new block modification to the history.
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+    }
+
+    // Remove old modifications older than maxTick
+    public void cleanup(int maxTick) {
+        while (!blockHistory.isEmpty() && maxTick - blockHistory.peekFirst().getTick() > 0) {
+            blockHistory.removeFirst();
+        }
+    }
+
+    // Get the size of the block history
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+
+public class PlayerBlockHistory {
+    private final ConcurrentLinkedDeque<BlockModification> blockHistory = new ConcurrentLinkedDeque<>();
+
+    // Add a new block modification to the history.
+    public void add(BlockModification modification) {
+        blockHistory.add(modification);
+    }
+
+    // Get all recent modifications (optionally filtered by a condition).
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+    public Iterable<BlockModification> getRecentModifications(Predicate<BlockModification> filter) {
+        return blockHistory.stream().filter(filter).toList(); // Java 8+ compatible
+    }
+
+    // Remove old modifications older than maxTick
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java (hunk 2 above)
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java [hunk 11]
```diff
@@ -1,27 +1,85 @@
...
 import ac.grim.grimac.utils.nmsutil.Materials;
 import com.github.retrooper.packetevents.protocol.player.GameMode;
 import com.github.retrooper.packetevents.protocol.world.states.type.StateType;
 import com.github.retrooper.packetevents.util.Vector3i;
 
+
+
 @CheckData(name = "AirLiquidPlace")
 public class AirLiquidPlace extends BlockPlaceCheck {
+
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java]:
```suggestion
```

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

**Comment by Axionize** [comment]
Ok I think that's everything, one last time @ManInMyVan do you approve?

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java [hunk 12]
```diff
@@ -1,27 +1,82 @@
...
 import ac.grim.grimac.utils.anticheat.update.BlockPlace;
+import ac.grim.grimac.utils.change.BlockModification;
 import ac.grim.grimac.utils.nmsutil.Materials;
 import com.github.retrooper.packetevents.protocol.player.GameMode;
 import com.github.retrooper.packetevents.protocol.world.states.type.StateType;
 import com.github.retrooper.packetevents.util.Vector3i;
 
 @CheckData(name = "AirLiquidPlace")
 public class AirLiquidPlace extends BlockPlaceCheck {
+
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java]:
```suggestion
```

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java [hunk 13]
```diff
@@ -1,27 +1,82 @@
...
     public AirLiquidPlace(GrimPlayer player) {
         super(player);
     }
-
+    /*
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java:21]:
```suggestion

    /*
```

File: src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java [hunk 14]
```diff
@@ -0,0 +1,46 @@
...
+    }
+
+    public int size() {
+        return blockHistory.size();
+    }
+
+    public void clear() {
+        blockHistory.clear();
+    }
+}
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/utils/change/PlayerBlockHistory.java]:
```suggestion
}

```

File: src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java [hunk 15]
```diff
@@ -1,27 +1,82 @@
...
+        // But for such tiny differences in legitness its not worth it.
+        Iterable<BlockModification> blockModifications = player.blockHistory.getRecentModifications((blockModification) -> currentTick - blockModification.getTick() < 2
+                && blockPos.equals(blockModification.getLocation())
+                && (blockModification.getCause() == BlockModification.Cause.START_DIGGING || blockModification.getCause() == BlockModification.Cause.HANDLE_NETTY_SYNC_TRANSACTION));
+
+        // Check if old block from instant breaking in same tick as the current placement was valid
+        // There should only be one block here for legit clients
+        for (BlockModification blockModification : blockModifications) {
+            StateType stateType = blockModification.getOldBlockContents().getType();
+            if (!(stateType.isAir() || Materials.isNoPlaceLiquid(stateType))) {
```
Comment (ManInMyVan) [inline src/main/java/ac/grim/grimac/checks/impl/scaffolding/AirLiquidPlace.java]:
```suggestion
            if (!stateType.isAir() && !Materials.isNoPlaceLiquid(stateType)) {
```

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

**Comment by Axionize** [comment]
@ManInMyVan is that it? Anything else? I will squash and merge if you have no objections.

**Review by ManInMyVan — APPROVED** [review]
