### PR TITLE
Fix some falses regarding camel sprinting

### LINKED ISSUE #2428: Sprint hit while on camel
### Describe the false positive and how to replicate it

1. Get on a camel
2. Start sprinting with it
3. Hit any entity while sprinting
4. Falses

Additionally falses NoSlow when done using the spear charge attack

### Grim Log

https://paste.grim.ac/nb4STeEr

### Grim version

2.3.73-1.21.11-dev-7e8fd6c

### Server version

1.21.11-72-main@cd445fd (2025-12-31T17:02:56Z) (Implementing API version 1.21.11-R0.1-SNAPSHOT)

### Client version

1,21.11

### Plugins/Mods

Only Grim

### PR DESCRIPTION
**Pull request by LaserSlime**
Fixes #2428, #2461 as well as sprinting on a camel while on low hunger.

Needs testing on older versions (I can't test those due to a weird packetevents error)

### CODE REVIEW

File: common/src/main/java/ac/grim/grimac/events/packets/PacketEntityAction.java [hunk 1]
```diff
@@ -35,9 +36,11 @@ public void onPacketReceive(PacketReceiveEvent event) {
             switch (action.getAction()) {
                 case START_SPRINTING:
                     player.isSprinting = true;
+                    player.camelSprintingState =  SprintingState.STARTED;
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/events/packets/PacketEntityAction.java]:
```suggestion
                    player.camelSprintingState = SprintingState.STARTED;
```

File: common/src/main/java/ac/grim/grimac/events/packets/PacketEntityAction.java [hunk 2]
```diff
@@ -35,9 +36,11 @@ public void onPacketReceive(PacketReceiveEvent event) {
...
                     break;
                 case STOP_SPRINTING:
                     player.isSprinting = false;
+                    player.camelSprintingState =  SprintingState.STOPPED;
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/events/packets/PacketEntityAction.java]:
```suggestion
                    player.camelSprintingState = SprintingState.STOPPED;
```

File: common/src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java [hunk 3]
```diff
@@ -102,6 +103,12 @@ public void onPacketReceive(PacketReceiveEvent event) {
                 entity.onMovement(isTickingReliably);
             }
         }
+
+        if(player.camelSprintingState == SprintingState.STOPPING) {
+            player.camelSprintingState = SprintingState.STOPPED;
+        } else if(player.camelSprintingState == SprintingState.STOPPED && player.isSprinting) { // For sprint desyncs
+            player.camelSprintingState = SprintingState.STARTED;
+        }
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java]:
```suggestion
        if (player.camelSprintingState == SprintingState.STOPPING) {
            player.camelSprintingState = SprintingState.STOPPED;
        } else if (player.camelSprintingState == SprintingState.STOPPED && player.isSprinting) { // For sprint desyncs
            player.camelSprintingState = SprintingState.STARTED;
        }
```

File: common/src/main/java/ac/grim/grimac/events/packets/PacketSelfMetadataListener.java [hunk 4]
```diff
@@ -87,6 +88,9 @@ public void onPacketSend(PacketSendEvent event) {
                         player.latencyUtils.addRealTimeTask(player.lastTransactionSent.get(), () -> {
                             player.isSwimming = isSwimming;
                             player.lastSprinting = isSprinting;
+                            if(!isSprinting) {
```
Comment (ManInMyVan) [inline common/src/main/java/ac/grim/grimac/events/packets/PacketSelfMetadataListener.java]:
```suggestion
                            if (!isSprinting) {
```

**Review by ManInMyVan — CHANGES_REQUESTED** [review]

**Comment by LaserSlime** [comment]
Should I also fix #2461 by exempting camels?

**Comment by LaserSlime** [comment]
Is there any reason why this isn't getting merged?

**Comment by Axionize** [comment]
Sorry about that @LaserSlime this is @Cyramek's domain and he hasn't had time to take a look yet.

File: common/src/main/java/ac/grim/grimac/player/GrimPlayer.java [hunk 5]
```diff
@@ -161,6 +160,7 @@ public class GrimPlayer implements GrimUser {
     // The client updates sprinting attribute at end of each tick
     // Don't false if the server update's the player's sprinting status
     public boolean lastSprintingForSpeed;
+    public SprintingState camelSprintingState = SprintingState.STOPPED;
```
Comment (Cyramek) [inline common/src/main/java/ac/grim/grimac/player/GrimPlayer.java]: this should go into VehicleData

**Comment by Cyramek** [comment]
other than that, it looks good, although I have a feeling there is a better way to do this, cotander probably can say more about sprint status issues

**Comment by Axionize** [comment]
@SamB440 ? Any comments to make on this besides moving the state?

**Comment by SamB440** [comment]
Can you explain a little why we are separately tracking a sprinting state for camels? As far as I'm aware sprinting in vehicles is based on packet sprinting state.

**Comment by LaserSlime** [comment]
Well it's been a while since I did all this, and I mostly figured it out through trial and error. The problem was that when using one of the existing sprinting variables, it would always false either when you start sprinting, or when you stop sprinting (due to an attack). At first I wanted to use a different sprinting state for when you're attacking, but it's of course a bad solution and didn't quite work. So eventually I figured it probably has nothing to do with attacking, but rather just the server stopping your sprint, which seems to behave differently than any other sprint state change for some reason. That's why when the server stops the sprint, it's slightly delayed until it actually counts as stopped.

**Comment by SamB440** [comment]
If it fixes issues, it's fine. Fixing packet sprinting likely requires more in depth work for 2.0, although I have a solid understanding of how sprinting works, but that's for another day to fix.

**Review by SamB440 — APPROVED** [review]
